import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";

export default function Home() {
  let [word, setWord] = useState("");
  let [results, setResults] = useState([]);
  const getResults = () => {
    console.log(word);
    fetch(`https://api.dictionaryapi.dev/api/v2/entries/en/${word}`).then(
      async (res) => {
        let result = await res.json();
        console.log(result);
        setResults(result);
      }
    );
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Word Dictionary</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Word Dictionary!</h1>
        <input
          onChange={(e) => {
            setWord(e.target.value);
          }}
          value={word}
          placeholder="type here"
        />
        <button onClick={getResults}>Search</button>

        <h3>Result:</h3>
        <div>
          {results.map((res) => {
            return (
              <>
                <div style={{textTransform:'uppercase'}}><b>{res.word}</b></div><br/><br/>
                {res.meanings.map((meaning) => {
                  return (
                    <>
                      ({meaning.partOfSpeech}) &nbsp;                
                      <span>{meaning.definitions[0].definition}</span><br/>
                      <em><small>example: {meaning.definitions[0].example}</small></em><br/><br/>
                      {meaning.definitions[0].synonyms.length ? <><em><small>synonyms: {meaning.definitions[0].synonyms.join(',')}</small></em><br/><br/></>:null}
                      {meaning.definitions[0].antonyms.length ? <><em><small>antonyms: {meaning.definitions[0].antonyms.join(',')}</small></em><br/><br/></>:null}
                    </>
                  );
                })}
              </>
            );
          })}
        </div>
      </main>
    </div>
  );
}
